### ISSUE TITLE
Tcl error when dragging from Chrome into a Tk window with menu bar

### ISSUE THREAD

**Issue by flopp** [petasis/tkdnd#34] opened 2019-07-03 09:23 UTC
I'm getting a Tcl error when dragging something from Chrome (e.g. the content of the URL bar) to a Tk window that also includes a menu bar. The error occurs exactly when hovering over the Tk window's border.

Here's a short video showing the behavior: https://www.youtube.com/watch?v=uFet-mn46RE

I was unable to reproduce the behavior with other applications than Chrome. Also, the menu bar in the Tk window seems to be necessary.

The error message:

```
bad window path name ""
bad window path name ""
    while executing
"winfo toplevel $win"
    (procedure "FindWindowWithCommonTypes" line 2)
    invoked from within
"FindWindowWithCommonTypes $drop_target $_typelist"
    (procedure "::tkdnd::generic::HandlePosition" line 32)
    invoked from within
"::tkdnd::generic::HandlePosition $drop_target $drag_source  $_pressedkeys $rootX $rootY"
    (procedure "tkdnd::xdnd::HandleXdndPosition" line 11)
    invoked from within
"tkdnd::xdnd::HandleXdndPosition {} 3050 441 10733902 54526183"
```

The error seems to be caused by `Tk_PathName(mouse_tkwin)` returning `NULL` in `unix/TkDND_XDND.c:471`.

Here's the very simple Tcl/Tk app with a menu bar and a `tkdnd::drop_target` used in the video:

```
package require tkdnd 2.9.2

menu .menu
.menu add cascade -label MENU
. configure -menu .menu

label .widget -text "LABEL"
pack .widget -expand 1 -fill both

tkdnd::drop_target register .widget *
bind .widget <<DropEnter>> {puts enter}

wm geometry . 300x200
```

Ubuntu 19.04, Tcl & Tk 8.6.9 (self compiled with default config), tkdnd 2.9.2 (git master of 2019-01-03), Chrome 75

**Comment by flopp** [comment] 2019-07-03 09:26
The issue can be avoided by checking for a `NULL` path name before evaluation `tkdnd::xdnd::HandleXdndPosition` in `TkDND_HandleXdndPosition` (similar to checking for a `NULL` `mouse_tkwin`).

**Comment by flopp** [comment] 2019-07-03 13:13
Tk seems to create a "wrapper window" without path name when adding a menu bar to a Tk window.
tkdnd somehow tries to work with this window as if it was a regular Tk window.

**Comment by petasis** [comment] 2019-07-12 18:14
Yes, Tk creates this window, but in reality the problem is in the chrome browser implementation (which probably does not implement the spec correctly). I am not sure how I can install chrome and test (it is not available as a package).

**Comment by petasis** [comment] 2019-07-12 18:22
Yes, I can reproduce the problem with chrome.

**Comment by petasis** [comment] 2019-07-12 18:28
I think the problem may be in TkDND_GetToplevelFromWrapper(), which does not seem to work correctly when a menu is in use.

**Comment by petasis** [comment] 2019-07-12 19:50
I have provided a fix on the current head. Can you please test that it solves the problem?
(It does in my test machine).

**Comment by flopp** [comment] 2019-07-13 07:30
Thanks! I'll be able to check the fix on Monday.

**Comment by flopp** [comment] 2019-07-15 07:23
Hmmm. On my machine, the patched `TkDND_GetToplevelFromWrapper` function actually returns the *wrong* toplevel window if there are two wrapper children.

After enabling the debug `printf` in `TkDND_HandleXdndPosition`, I get

```
mouse_win: 0x55577ae3f550 (.#menu) (1477, 969 0x55577ae3ef50 (null)) i=0x55577ab11070
mouse_win: 0x55577ae3f550 (.#menu) (1476, 969 0x55577ae3ef50 (null)) i=0x55577ab11070
mouse_win: 0x55577ae3f550 (.#menu) (1476, 970 0x55577ae3ef50 (null)) i=0x55577ab11070
...
```
when dragging something into `.widget` of `tests/bug34.tcl` => so, TkDND actually thinks that the mouse is inside the window's menu.

If I change `TkDND_GetToplevelFromWrapper` to return first child (in case there are two children), I get the  expected

```
mouse_win: 0x55ac0a943240 (.widget) (1355, 196 0x55ac0a957280 (null)) i=0x55ac0a62a070
mouse_win: 0x55ac0a943240 (.widget) (1355, 196 0x55ac0a957280 (null)) i=0x55ac0a62a070
mouse_win: 0x55ac0a943240 (.widget) (1355, 196 0x55ac0a957280 (null)) i=0x55ac0a62a070
...
```

So, maybe the order of children is not fixed?

**Comment by petasis** [comment] 2019-07-15 07:34
Maybe. In my Linux, the menu is always the first child. What does xwinfo -tree returns in your case?

**Comment by flopp** [comment] 2019-07-15 07:37
```
$ xwininfo -tree

xwininfo: Window id: 0x4a00037 "test.tcl"

  Root window id: 0x1d2 (the root window) (has no name)
  Parent window id: 0xc01b7a (has no name)
     2 children:
     0x4a00036 (has no name): ()  300x32+0+0  +70+802
     0x4a00009 (has no name): ()  300x200+0+32  +70+834
        1 child:
        0x4a0003d (has no name): ()  300x200+0+0  +70+834
```

=> geometry-wise, the first child (`0x4a00036`) looks like the menu.

**Comment by flopp** [comment] 2019-07-15 07:39
Replacing the two `if`s in `TkDND_GetToplevelFromWrapper` by

```
/* If we have a wrapper window with multiple children, use the first child
   * that is a "toplevel" window. */
  for (i = 0; i < nchildren_return; ++i) {
    toplevel = Tk_IdToWindow(Tk_Display(tkwin), children_return[i]);
    if (Tk_IsTopLevel(toplevel)) {
      break;
    }
  }
```

does the job for me, because `Tk_IsTopLevel` is `!= 0` for the second child.

**Comment by flopp** [comment] 2019-07-15 07:41
Wait... So, according to my `xwininfo` output, the second child *is* the correct one!

**Comment by flopp** [comment] 2019-07-15 07:49
Ok, next try:

`xwininfo -tree` prints

```
  Root window id: 0x1d2 (the root window) (has no name)
  Parent window id: 0xc01edd (has no name)
     2 children:
     0x4a00036 (has no name): ()  300x32+0+0  +70+802
     0x4a00009 (has no name): ()  300x200+0+32  +70+834
        1 child:
        0x4a0003d (has no name): ()  300x200+0+0  +70+834
```

But the order of `children_return` in `TkDND_GetToplevelFromWrapper` is exactly the opposite:

```
children_return[0]=0x4a00009 Tk_PathName=. Tk_IsTopLevel=2
children_return[1]=0x4a00036 Tk_PathName=.#menu Tk_IsTopLevel=0
```

=> `XQueryTree` does not use the same order as `xwininfo`

**Comment by petasis** [comment] 2019-07-15 10:39
I have committed the fix you provided for selecting the toplevel window. However, now there is another problem: what happens if someone drops something on the menu... This is a different tree, outside the tree of the toplevel.

This needs more thought.

**Comment by flopp** [comment] 2019-07-15 11:52
Thanks!

I hope that using the main menu (or even some specific sub-menu) as a drop target is not a common use case, so we can safely ignore that. Getting these GUI details right is really complicated :(

**Closed** 2019-07-15 14:20 UTC
